name: Push GHCR Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -f ./Dockerfile ./server --tag jarvis:latest

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin

    - name: Push image
      run: |
        REMOTE_NAME="ghcr.io/${{ github.repository_owner }}/jarvis:latest"
        docker tag jarvis:latest $REMOTE_NAME
        docker push $REMOTE_NAME
