name: Linter
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v2.0
      - uses: azure/k8s-lint@v1
        with:
           lintType: dryrun
           manifests: |
              rollout.yml
