name: Linter
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Rollout YAML
      uses: jacobtomlinson/gha-lint-yaml@master
      with:
        path: rollout.yaml
